name: Build Release Artifacts
on:
  push:
    branches:
    - frenchy64-experiments
  release:
    types: [created]
env:
  CLOJURE_CLI_VERSION: '1.10.3.839'
  JAVA_VERSION: '14'
jobs:
  build:
    strategy:
      matrix:
        include:
        - os: ubuntu-latest
          asset_name: cljfx-hn_1.0-1_amd64.deb
          jpackage_platform: linux
        - os: macos-latest
          asset_name: cljfx-hn-1.0.dmg
          jpackage_platform: mac
        - os: windows-latest
          asset_name: cljfx-hn-1.0.exe
          jpackage_platform: windows
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ env.JAVA_VERSION }}
      - uses: DeLaGuardo/setup-clojure@12f4eac60789f0256331cd11c6072e48567953b4
        with:
          cli: ${{ env.CLOJURE_CLI_VERSION }}

      # uberjar
      - run: clojure -X:uberjar
        if: ${{ matrix.os != 'windows-latest' }}
        shell: bash
      - run: clojure -X:uberjar
        if: ${{ matrix.os == 'windows-latest' }}
        shell: powershell

      - run: jpackage @jpackage/common "@jpackage/${JPACKAGE_PLATFORM}"
        shell: bash
        env:
          JPACKAGE_PLATFORM: ${{ matrix.jpackage_platform }}
      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ matrix.asset_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
