name: Build Release Artifacts
on:
  push:
    tags:
      - 'v*'
env:
  CLOJURE_CLI_VERSION: '1.10.3.839'
  JAVA_VERSION: '16'
jobs:
  release:
    strategy:
      matrix:
        include:
        - os: ubuntu-latest
          asset_name_template: cljfx-hn_VERSION-1_amd64.deb
          jpackage_platform: linux
        - os: macos-latest
          asset_name_template: cljfx-hn-VERSION.dmg
          jpackage_platform: mac
        - os: windows-latest
          asset_name_template: cljfx-hn-VERSION.exe
          jpackage_platform: windows
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2/repository
            ~/.gitlibs
          key: ${{ runner.os }}-clojure-${{ hashFiles('deps.edn') }}
          restore-keys: |
            ${{ runner.os }}-clojure-

      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: ${{ env.JAVA_VERSION }}
      - uses: DeLaGuardo/setup-clojure@3.3
        with:
          cli: ${{ env.CLOJURE_CLI_VERSION }}

      # uberjar
      - run: clojure -X:uberjar
        if: ${{ matrix.os != 'windows-latest' }}
        shell: bash
      - run: clojure -X:uberjar
        if: ${{ matrix.os == 'windows-latest' }}
        shell: powershell

      - run: |
          APP_VERSION=${GITHUB_REF/refs\/tags\/v/} #for sharing within this step
          echo "APP_VERSION=${APP_VERSION}" >> $GITHUB_ENV #for sharing between steps
          # substite VERSION in asset_name_template's with current tag version
          echo "ASSET_NAME=${ASSET_NAME_TEMPLATE/VERSION/${APP_VERSION}}" >> $GITHUB_ENV
        shell: bash
        env:
          ASSET_NAME_TEMPLATE: ${{ matrix.asset_name_template }}
      - run: jpackage @jpackage/common "@jpackage/${JPACKAGE_PLATFORM}" --app-version $APP_VERSION
        shell: bash
        env:
          JPACKAGE_PLATFORM: ${{ matrix.jpackage_platform }}
      - uses: softprops/action-gh-release@9729932bfb75c05ad1f6e3a729294e05abaa7001
        with:
          files: ${{ env.ASSET_NAME }}
          name: Release v${{ env.APP_VERSION }}
          fail_on_unmatched_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
